### ISSUE TITLE
errors in followers and following page

### ISSUE THREAD

**Issue by arnellebalane** [josephclint/v-Hub#11]
![image](https://cloud.githubusercontent.com/assets/1428598/8977524/8eb8f9e8-36cc-11e5-82db-a109a3edee83.png)

![image](https://cloud.githubusercontent.com/assets/1428598/8977535/9951067a-36cc-11e5-891d-3405b8f74bb0.png)

**Comment by miguelvictor** [comment]
Sa erd btaw kuya, kay wala man ni naapil, so i think low priority ra ni sya

**Comment by arnellebalane** [comment]
okay, make it show a proper 404 page nalang, instead of showing that error :+1:

**Comment by miguelvictor** [comment]
btw kuya, ako ni gipuno sa models, kay part man jud ni sa project haha nga nakalimtan sa erd
