### ISSUE TITLE
errors already shown on page load

### ISSUE THREAD

**Issue by arnellebalane** [josephclint/v-Hub#13]
![image](https://cloud.githubusercontent.com/assets/1428598/8977619/5869b2a0-36cd-11e5-8296-463866fd599e.png)

**Comment by arnellebalane** [comment]
how to replicate:
- make an initial submission that will cause an error (e.g. don't select a category)
- the error messages will be displayed
- navigate away from the page and visit it again
- the errors are still there

**Comment by miguelvictor** [comment]
fixed on this commit : https://github.com/josephclint/v-Hub/commit/05bd89c02ce220bb51e42c12239661ad5ad60373
