### ISSUE TITLE
who is this?

### ISSUE THREAD

**Issue by arnellebalane** [josephclint/v-Hub#17]
![image](https://cloud.githubusercontent.com/assets/1428598/8978281/3e649888-36d3-11e5-9ad4-bafec3927893.png)

**Comment by migzisreallywewwhat** [comment]
ako ani kuya, katong wala nako naset ang git config user email ug name

**Comment by miguelvictor** [comment]
ako ani kuya, katong wala nako naset ang git config user email ug name
