### ISSUE TITLE
clicking on categories in home page just redirects to the the home page

### ISSUE THREAD

**Issue by arnellebalane** [josephclint/v-Hub#9]
![image](https://cloud.githubusercontent.com/assets/1428598/8977467/16658ccc-36cc-11e5-834c-7152d7c99425.png)

**Comment by ghost** [comment]
Kuya, there is already a design for the categories page but it is not yet integrated in the website. As for the custom video player, the video and clipping controls are already designed and the positioning of the markers for the clipping and pictures of the users that made the comments are done but they are still not integrated. Gi.upload lang sa nako ang files for the custom player sa trello kuya.
